name: 'Terraform Test Deployment'

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_VAR_tailscale_key: ${{ secrets.TAILSCALE_KEY }}
      TF_VAR_infura_url: ${{ secrets.INFURA_URL }}
      TF_VAR_log_analytics_workspace: ${{secrets.LOG_ANALYTICS_WORKSPACE}}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform-test

#    - name: Terraform Plan
#      run: terraform plan
#      working-directory: ./terraform-test

#    - name: Terraform Apply
#      run: terraform apply -auto-approve
#      working-directory: ./terraform-test

      # Add the Destroy step
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./terraform-test